import expert1 from "../../assets/images/expert1.png";// src/data/expertsData.js
export const expertsData = [
  {
    id: 1,
    name: "Tony Stark",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 2,
    name: "Steve Rogers",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 3,
    name: "Natasha Romanoff",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 4,
    name: "Peter Parker",
    role: "Vocal Trainer",
    experience: "11 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 5,
    name: "Bruce Banner",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 6,
    name: "Clint Barton",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 7,
    name: "Wanda Maximoff",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 8,
    name: "Carol Danvers",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 270/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 9,
    name: "James Rhodes",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 10,
    name: "Scott Lang",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 11,
    name: "Hope Van Dyne",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 12,
    name: "Stephen Strange",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 13,
    name: "Sam Wilson",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 14,
    name: "Peter Quill",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 15,
    name: "Bucky Barnes",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
  {
    id: 16,
    name: "Peggy Carter",
    role: "Vocal Trainer",
    experience: "10 Years of experience",
    speaks: "English, Arabic x2",
    fee: "QAR 250/hr",
    students: "All level students",
    image: expert1,
  },
];
